## Potential Nutrient intake

In [ ]:
# Install package to allow import from REDCap API
from redcap import Project
import pandas as pd
import numpy as np
import os
from tqdm.notebook import tqdm  # progress bar

# Connecting to GFDx Redcap API
api_key = os.environ.get("APIKEY")

URL = 'https://redcap.emory.edu/api/'
project = Project(URL, api_key)

Collecting PyCap
  Downloading https://files.pythonhosted.org/packages/80/24/34d5ddf1220494dc0b6161940b4d1158ea6fa4c68a699af8d1901f74a6c4/PyCap-1.1.2-py3-none-any.whl
Collecting semantic-version>=2.3.1
  Downloading https://files.pythonhosted.org/packages/a5/15/00ef3b7888a10363b7c402350eda3acf395ff05bebae312d1296e528516a/semantic_version-2.8.5-py2.py3-none-any.whl
Requirement already satisfied: requests>=1.0.0 in /usr/local/lib/python3.6/dist-packages (from PyCap) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->PyCap) (2020.11.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->PyCap) (1.24.3)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->PyCap) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.6/dist-packages (from requests>=1.0.0->PyCap) (2.10)
Installing collected packages: semantic-version, PyCap
Successfully installed PyCap-1.1.2 semantic-version-2.8.5

In [ ]:
# Pulls out variables of interest
fields_of_interest = ['country_code', 'nutrient_level', 'latest_intake_api', 'ip_pc_api', 'compliance_pc_api', 'standard_nutrient']
subset = project.export_records(fields=fields_of_interest, format='df')

                               redcap_repeat_instrument  ...  compliance_pc_api
country_code redcap_event_name                           ...
1.0          all_foods_arm_1                        NaN  ...                NaN
             maize_flour_arm_1                      NaN  ...                NaN
             oil_arm_1                              NaN  ...                NaN
             rice_arm_1                             NaN  ...                NaN
             salt_arm_1                             NaN  ...                NaN

[5 rows x 7 columns]

In [ ]:
# Reset index
df=subset
df.reset_index(inplace=True)

   country_code  redcap_event_name  ... ip_pc_api  compliance_pc_api
0           1.0    all_foods_arm_1  ...       NaN                NaN
1           1.0  maize_flour_arm_1  ...       NaN                NaN
2           1.0          oil_arm_1  ...       NaN                NaN
3           1.0         rice_arm_1  ...       NaN                NaN
4           1.0         salt_arm_1  ...       NaN                NaN

[5 rows x 9 columns]

In [ ]:
df = df[df.country_code != 999.0] # Remove country code 999

In [ ]:
food_list = ['maize_flour_arm_1', 'wheat_flour_arm_1', 'rice_arm_1', 'salt_arm_1', 'oil_arm_1',
                'maize_flour_arm_2', 'wheat_flour_arm_2', 'rice_arm_2', 'salt_arm_2', 'oil_arm_2']
df2 = df[df.redcap_event_name.isin(food_list)]
df1 = df2[df.redcap_repeat_instrument == 'nutrients_compounds']

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:4: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  after removing the cwd from sys.path.

    country_code redcap_event_name  ... ip_pc_api  compliance_pc_api
12           1.0        salt_arm_1  ...       NaN                NaN
13           1.0        salt_arm_2  ...       NaN                NaN
26           2.0         oil_arm_1  ...       NaN                NaN
27           2.0         oil_arm_1  ...       NaN                NaN
28           2.0        salt_arm_1  ...       NaN                NaN

[5 rows x 9 columns]

In [ ]:
df_copy1 = df1

# 1. Nutrient Intake
def intake_pc(row):
    try: 
        return (float(row.nutrient_level) / 1000 * (float(row.latest_intake_api)))
    except ValueError:
        return 'Not enough data to calculate'

df_copy1['nutrient_intake'] = df_copy1.apply(lambda row: intake_pc(row), axis=1)

# 2. Nutrient Intake, Adjusted
def intake_adj_pc(row):
    if row.nutrient_intake == 'Not enough data to calculate':
        return 'Not enough data to calculate'
    else:
        try: 
            return (float(row.nutrient_intake) * (float(row.ip_pc_api) / 100) * (float(row.compliance_pc_api) / 100))
        except ValueError:
            return 'Not enough data to calculate'

df_copy1['nutrient_intake_adj'] = df_copy1.apply(lambda row: intake_adj_pc(row), axis=1)

# 3. EAR
def ear_pc(row):
    if row.nutrient_intake == 'Not enough data to calculate':
        return 'Not enough data to calculate'
    elif row.standard_nutrient == 1:
        try: 
            return (float(row.nutrient_intake) / 1.1 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 2:
        try: 
            return (float(row.nutrient_intake) / 0.002 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 3:
        try: 
            return (float(row.nutrient_intake) / 800 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 4:
        try: 
            return (float(row.nutrient_intake) / 3 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 5:
        try: 
            return (float(row.nutrient_intake) / 0.4 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 6:
        try: 
            return (float(row.nutrient_intake) / 0.095 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 7:
        try: 
            return (float(row.nutrient_intake) / 8.1 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 8:
        try: 
            return (float(row.nutrient_intake) / 11 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 9:
        try: 
            return (float(row.nutrient_intake) / 0.9 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 10:
        try: 
            return (float(row.nutrient_intake) / 0.045 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 11:
        try: 
            return (float(row.nutrient_intake) / 0.9 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 12:
        try: 
            return (float(row.nutrient_intake) / 0.5 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 13:
        try: 
            return (float(row.nutrient_intake) / 0.01 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 14:
        try: 
            return (float(row.nutrient_intake) / 12 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 15:
        try: 
            return (float(row.nutrient_intake) / 6.8 * 100)
        except ValueError:
            return 'Not enough data to calculate'

df_copy1['nutrient_ear_pc'] = df_copy1.apply(lambda row: ear_pc(row), axis=1)

# 3. EAR, Adjusted
def ear_adj_pc(row):
    if row.nutrient_intake_adj == 'Not enough data to calculate':
        return 'Not enough data to calculate'
    elif row.standard_nutrient == 1:
        try: 
            return (float(row.nutrient_intake_adj) / 1.1 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 2:
        try: 
            return (float(row.nutrient_intake_adj) / 0.002 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 3:
        try: 
            return (float(row.nutrient_intake_adj) / 800 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 4:
        try: 
            return (float(row.nutrient_intake_adj) / 3 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 5:
        try: 
            return (float(row.nutrient_intake_adj) / 0.4 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 6:
        try: 
            return (float(row.nutrient_intake_adj) / 0.095 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 7:
        try: 
            return (float(row.nutrient_intake_adj) / 8.1 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 8:
        try: 
            return (float(row.nutrient_intake_adj) / 11 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 9:
        try: 
            return (float(row.nutrient_intake_adj) / 0.9 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 10:
        try: 
            return (float(row.nutrient_intake_adj) / 0.045 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 11:
        try: 
            return (float(row.nutrient_intake_adj) / 0.9 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 12:
        try: 
            return (float(row.nutrient_intake_adj) / 0.5 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 13:
        try: 
            return (float(row.nutrient_intake_adj) / 0.01 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 14:
        try: 
            return (float(row.nutrient_intake_adj) / 12 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 15:
        try: 
            return (float(row.nutrient_intake_adj) / 6.8 * 100)
        except ValueError:
            return 'Not enough data to calculate'

df_copy1['nutrient_ear_pc_adj'] = df_copy1.apply(lambda row: ear_adj_pc(row), axis=1)

# 5. UL
def ul_pc(row):
    if row.standard_nutrient == 2 or row.standard_nutrient == 9 or row.standard_nutrient == 11:
        return 'No UL for this nutrient'
    elif row.nutrient_intake == 'Not enough data to calculate':
        return 'Not enough data to calculate'
    elif row.standard_nutrient == 1:
        try: 
            return (float(row.nutrient_intake) / 100 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 3:
        try: 
            return (float(row.nutrient_intake) / 2500 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 4:
        try: 
            return (float(row.nutrient_intake) / 10 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 5:
        try: 
            return (float(row.nutrient_intake) / 1 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 6:
        try: 
            return (float(row.nutrient_intake) / 0.6 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 7:
        try: 
            return (float(row.nutrient_intake) / 45 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 8:
        try: 
            return (float(row.nutrient_intake) / 35 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 10:
        try: 
            return (float(row.nutrient_intake) / 0.04 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 12:
        try: 
            return (float(row.nutrient_intake) / 3 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 13:
        try: 
            return (float(row.nutrient_intake) / 0.1 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 14:
        try: 
            return (float(row.nutrient_intake) / 1000 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 15:
        try: 
            return (float(row.nutrient_intake) / 40 * 100)
        except ValueError:
            return 'Not enough data to calculate'

df_copy1['nutrient_ul_pc'] = df_copy1.apply(lambda row: ul_pc(row), axis=1)

# 6. UL, Adjusted
def ul_adj_pc(row):
    if row.standard_nutrient == 2 or row.standard_nutrient == 9 or row.standard_nutrient == 11:
        return 'No UL for this nutrient'
    elif row.nutrient_intake_adj == 'Not enough data to calculate':
        return 'Not enough data to calculate'
    elif row.standard_nutrient == 1:
        try: 
            return (float(row.nutrient_intake_adj) / 100 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 3:
        try: 
            return (float(row.nutrient_intake_adj) / 2500 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 4:
        try: 
            return (float(row.nutrient_intake_adj) / 10 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 5:
        try: 
            return (float(row.nutrient_intake_adj) / 1 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 6:
        try: 
            return (float(row.nutrient_intake_adj) / 0.6 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 7:
        try: 
            return (float(row.nutrient_intake_adj) / 45 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 8:
        try: 
            return (float(row.nutrient_intake_adj) / 35 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 10:
        try: 
            return (float(row.nutrient_intake_adj) / 0.04 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 12:
        try: 
            return (float(row.nutrient_intake_adj) / 3 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 13:
        try: 
            return (float(row.nutrient_intake_adj) / 0.1 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 14:
        try: 
            return (float(row.nutrient_intake_adj) / 1000 * 100)
        except ValueError:
            return 'Not enough data to calculate'
    elif row.standard_nutrient == 15:
        try: 
            return (float(row.nutrient_intake_adj) / 40 * 100)
        except ValueError:
            return 'Not enough data to calculate'

df_copy1['nutrient_ul_pc_adj'] = df_copy1.apply(lambda row: ul_adj_pc(row), axis=1)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  # Remove the CWD from sys.path while we load stuff.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:104: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:186: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:255: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:324: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
final=df_copy1

final.drop(['nutrient_level'], axis=1, inplace=True)
final.drop(['latest_intake_api'], axis=1, inplace=True)
final.drop(['ip_pc_api'], axis=1, inplace=True)
final.drop(['compliance_pc_api'], axis=1, inplace=True)
final.drop(['standard_nutrient'], axis=1, inplace=True)

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:4174: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [ ]:
final["country_code"] = final.country_code.apply(lambda x: int(x))
final["redcap_repeat_instance"] = final.redcap_repeat_instance.apply(lambda x: int(x))

# Formats data into acceptable table for import into REDCap
final2 = final.set_index(['country_code', 'redcap_event_name'])

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
# FINAL IMPORT - Import to REDCap through API
project.import_records(final2)

{'count': 153}